### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by matthewelwell**

### CODE REVIEW

**Comment by veselfil** [comment]
Hi, are there any plans to merge this? I'd like to contribute some changes, but I'm not sure whether I should base them on the 4.0.0 branch or the currently released one.

**Comment by dabeeeenster** [comment]
> Hi, are there any plans to merge this? I'd like to contribute some changes, but I'm not sure whether I should base them on the 4.0.0 branch or the currently released one.

yep its very close - if you are going to do any PRs would advise doing them against this branch. What sort of things did you have in mind?

**Comment by veselfil** [comment]
I was going to add analytics support, however looking at the PR now, it seems it's already a part of this PR, so that's great. Is there anything I could do to get the PR merged sooner then?

**Comment by dabeeeenster** [comment]
> I was going to add analytics support, however looking at the PR now, it seems it's already a part of this PR, so that's great. Is there anything I could do to get the PR merged sooner then?

We're about to deploy our Edge API into production at which point we will be releasing all our v2 SDKs - this is being worked on hard and very close! 

We have added semantic versioning in our flag engine (https://github.com/Flagsmith/flagsmith-engine/search?q=semver in python) - this would be a great addition!

**Pull request merged**
