### PR TITLE
chore: test support for other .NET versions

### PR DESCRIPTION
**Pull request by matthewelwell**

### CODE REVIEW

**Comment by Aniketsingh1** [comment]
it is not working with ASP.NET MVC application with 4.7.2

**Comment by Aniketsingh1** [comment]
You have any suggestions for that?

**Review by novakzaballa — APPROVED** [review]
LGTM

**Comment by gagantrivedi** [comment]
> it is not working with ASP.NET MVC application with 4.7.2

One for @novakzaballa

**Comment by matthewelwell** [comment]
> > it is not working with ASP.NET MVC application with 4.7.2
> 
> One for @novakzaballa

There is a separate issue open for this [here](https://github.com/Flagsmith/flagsmith-dotnet-client/issues/76). I will merge this PR and we can handle that issue separately as it requires more work to set up the test environment in .NET Framework.

**Pull request merged**
